version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: campeche_mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: weatherAPI
      MARIADB_USER: weather
      MARIADB_PASSWORD: weatherpass
    ports:
      - "3307:3306"   # host:container
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: campeche_api
    restart: unless-stopped
    env_file:
      - .env.docker
    depends_on:
      - mariadb
    ports:
      - "8000:8000"
    # si usas hot-reload en desarrollo:
    # volumes:
    #   - ./:/app

volumes:
  db_data:
